collect_metrics:
  - cpu/request
  - cpu/usage_rate
  - memory/request
  - memory/usage
  - network/rx_rate
  - network/tx_rate

hawkular_metrics_client:
  concurrency: 10
  scheme: https
  port: 443
  path: hawkular/metrics
  token: WFVJzG17om_eDGeJq3M_bm9jKHVoCVLPW0VNlwHAQAw
